USE [master]
GO
/****** Object:  Database [AjaxCrud]    Script Date: 25-Mar-21 4:05:41 PM ******/
CREATE DATABASE [AjaxCrud]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AjaxCrud', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\AjaxCrud.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AjaxCrud_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\AjaxCrud_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [AjaxCrud] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AjaxCrud].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AjaxCrud] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AjaxCrud] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AjaxCrud] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AjaxCrud] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AjaxCrud] SET ARITHABORT OFF 
GO
ALTER DATABASE [AjaxCrud] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AjaxCrud] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AjaxCrud] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AjaxCrud] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AjaxCrud] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AjaxCrud] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AjaxCrud] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AjaxCrud] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AjaxCrud] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AjaxCrud] SET  ENABLE_BROKER 
GO
ALTER DATABASE [AjaxCrud] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AjaxCrud] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AjaxCrud] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AjaxCrud] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AjaxCrud] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AjaxCrud] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [AjaxCrud] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AjaxCrud] SET RECOVERY FULL 
GO
ALTER DATABASE [AjaxCrud] SET  MULTI_USER 
GO
ALTER DATABASE [AjaxCrud] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AjaxCrud] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AjaxCrud] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AjaxCrud] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AjaxCrud] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AjaxCrud] SET QUERY_STORE = OFF
GO
USE [AjaxCrud]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [AjaxCrud]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 25-Mar-21 4:05:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Test]    Script Date: 25-Mar-21 4:05:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Test](
	[SL] [int] IDENTITY(1,1) NOT NULL,
	[AccountNumber] [nvarchar](50) NULL,
 CONSTRAINT [PK_Test] PRIMARY KEY CLUSTERED 
(
	[SL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[transactions]    Script Date: 25-Mar-21 4:05:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[transactions](
	[TransactionID] [int] IDENTITY(1,1) NOT NULL,
	[AccountNumber] [nvarchar](12) NULL,
	[BeneficiaryName] [nvarchar](100) NULL,
	[BankName] [nvarchar](100) NULL,
	[SWIFTCode] [nvarchar](11) NULL,
	[Amount] [int] NOT NULL,
	[EntryDate] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_transactions] PRIMARY KEY CLUSTERED 
(
	[TransactionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[transactions] ADD  DEFAULT ('0001-01-01T00:00:00.0000000') FOR [EntryDate]
GO
USE [master]
GO
ALTER DATABASE [AjaxCrud] SET  READ_WRITE 
GO
